# Generated by Django 5.2.4 on 2025-08-10 12:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_category_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Кубики LEGO, Оси и шестерни, Пластины', max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории товаров', verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300px', null=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('icon', models.CharField(blank=True, help_text='Эмодзи для отображения в интерфейсе', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли категорию на сайте', verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'products_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название товара', max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=200, unique=True, verbose_name='URL')),
                ('sku', models.CharField(help_text='Уникальный код товара', max_length=50, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(help_text='Подробное описание характеристик и применения', verbose_name='Описание товара')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для карточки товара', max_length=255, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена до скидки (если есть)', max_digits=10, null=True, verbose_name='Старая цена')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Доступное количество для продажи', verbose_name='Количество на складе')),
                ('min_stock', models.PositiveIntegerField(default=5, help_text='При достижении этого количества товар помечается как заканчивающийся', verbose_name='Минимальный запас')),
                ('image', models.ImageField(blank=True, help_text='Главное изображение товара', null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли товар на сайте', verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать в рекомендуемых товарах', verbose_name='Рекомендуемый')),
                ('is_new', models.BooleanField(default=False, help_text='Показывать как новый товар', verbose_name='Новинка')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Вес товара в граммах', max_digits=8, null=True, verbose_name='Вес (г)')),
                ('dimensions', models.CharField(blank=True, help_text='Например: 2x4, 1x1, 4x6', max_length=100, verbose_name='Размеры')),
                ('colors', models.JSONField(blank=True, help_text='Список доступных цветов в формате JSON', null=True, verbose_name='Доступные цвета')),
                ('tags', models.JSONField(blank=True, help_text='Теги для поиска и фильтрации', null=True, verbose_name='Теги')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='Выберите категорию для товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products_products',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение товара', upload_to='products/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO', max_length=200, verbose_name='Альтернативный текст')),
                ('is_primary', models.BooleanField(default=False, help_text='Показывать как главное изображение товара', verbose_name='Основное изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'products_product_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
